# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  Exclude:
      - 'spec/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 11
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperator:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

#Style/StringLiterals:
#  Enabled: false

Style/SignalException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Style/LambdaCall:
  Exclude:
    - 'app/views/**/*.jbuilder'

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/ClassAndModuleChildren:
  Enabled: false

Layout/AlignParameters:
  Enabled: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Naming/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Style/Lambda:
  Enabled: false

Rails/FindEach:
  Enabled: false

Style/GuardClause:
  Enabled: false
